### ISSUE TITLE
Erro ao aceder ao IGRP Studio

### ISSUE THREAD

**Issue by paulopereiralr** [IMarcelF/IGRP-Framework#1758]
![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/140891231/127daae5-f32f-47cd-b16a-2d54332941c2)

          	
		            	java.lang.NullPointerException: Cannot invoke "jakarta.servlet.http.HttpServletRequest.getParameter(String)" because the return value of "nosi.core.webapp.Igrp.getRequest()" is null
	at nosi.core.webapp.Core.getParam(Core.java:1433)
	at nosi.core.webapp.Core.setMessageError(Core.java:3158)
	at nosi.base.ActiveRecord.BaseActiveRecord.showMessage(BaseActiveRecord.java:1339)
	at nosi.base.ActiveRecord.BaseActiveRecord.setError(BaseActiveRecord.java:1315)
	at nosi.base.ActiveRecord.BaseActiveRecord.all(BaseActiveRecord.java:946)
	at nosi.base.ActiveRecord.BaseActiveRecord.one(BaseActiveRecord.java:909)
	at nosi.base.ActiveRecord.BaseActiveRecord.findOne(BaseActiveRecord.java:901)
	at nosi.webapps.igrp.dao.IGRPBaseActiveRecord.findOne(IGRPBaseActiveRecord.java:23)
	at nosi.webapps.igrp.dao.User.findIdentityById(User.java:216)
	at nosi.core.authentication.AuthenticationManager.getIdentityFromToken(AuthenticationManager.java:80)
	at nosi.core.authentication.AuthenticationManager.isSessionExists(AuthenticationManager.java:42)
	at nosi.core.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at nosi.core.filter.EncodingFilter.doFilter(EncodingFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at nosi.core.filter.ThreadLocalFilter.doFilter(ThreadLocalFilter.java:29)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at io.smallrye.metrics.jaxrs.JaxRsMetricsServletFilter.doFilter(JaxRsMetricsServletFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:870)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1762)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NOSiopen** [comment]
Filter melhorado
